In [86]:
import numpy as np

In [87]:
#creating an array
arr1=np.array([1,22,57,33])#1D array
print(arr1)
print(type(arr1))
print(arr1.shape)

[ 1 22 57 33]
<class 'numpy.ndarray'>
(4,)


In [88]:
print(arr1.reshape(1,4))#1 row and 4 columns

[[ 1 22 57 33]]


In [89]:
arr2=np.array([[5,19,91,859,1,9]])
arr2.shape

(1, 6)

In [90]:
np.arange(0,13,3).reshape(5,1)

array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12]])

In [91]:
print("arr1:", arr1)
print("  shape:", arr1.shape)
print("  ndim:", arr1.ndim)
print("  size:", arr1.size)
print("  dtype:", arr1.dtype)
print("  itemsize:", arr1.itemsize)
print("  nbytes:", arr1.nbytes)
print("  strides:", arr1.strides)

print("\narr2:", arr2)
print("  shape:", arr2.shape)
print("  ndim:", arr2.ndim)
print("  size:", arr2.size)
print("  dtype:", arr2.dtype)
print("  itemsize:", arr2.itemsize)
print("  nbytes:", arr2.nbytes)
print("  strides:", arr2.strides)

arr1: [ 1 22 57 33]
  shape: (4,)
  ndim: 1
  size: 4
  dtype: int64
  itemsize: 8
  nbytes: 32
  strides: (8,)

arr2: [[  5  19  91 859   1   9]]
  shape: (1, 6)
  ndim: 2
  size: 6
  dtype: int64
  itemsize: 8
  nbytes: 48
  strides: (48, 8)


In [92]:
#Numpy vectorized operation
arr2=np.array([48,5,851,84])
print("addition",arr1+arr2)
print("sub",arr1-arr2)
print("mul",arr1*arr2)
print("div",arr1/arr2)

addition [ 49  27 908 117]
sub [ -47   17 -794  -51]
mul [   48   110 48507  2772]
div [0.02083333 4.4        0.06698002 0.39285714]


In [93]:
#Universal func
print(np.sin(arr1)) #sine
print(np.log(arr1)) #logrithm
print(np.sqrt(arr1))
print(np.exp(arr1))


[ 0.84147098 -0.00885131  0.43616476  0.99991186]
[0.         3.09104245 4.04305127 3.49650756]
[1.         4.69041576 7.54983444 5.74456265]
[2.71828183e+00 3.58491285e+09 5.68572000e+24 2.14643580e+14]


In [94]:
#Array slicing and Indexing
arr=np.array([[65,1,8,9],[19,4,19,91],[4,1,9,4]])
print(f"{arr.shape} \n")
print(arr)
print("\n",arr[0][2]) #1st row and 3rd element
print("\n",arr[1:])#2nd to last row
print("\n",arr[1:,2:])
print("\n",arr[1:,1:3])

(3, 4) 

[[65  1  8  9]
 [19  4 19 91]
 [ 4  1  9  4]]

 8

 [[19  4 19 91]
 [ 4  1  9  4]]

 [[19 91]
 [ 9  4]]

 [[ 4 19]
 [ 1  9]]


In [95]:
#Modify the elements
arr[1:,2:3]=100
print(arr)

[[ 65   1   8   9]
 [ 19   4 100  91]
 [  4   1 100   4]]


In [98]:
# Statistical concepts using numpy

print("Statistics for arr1:", arr1)
print("Mean:", np.mean(arr1))
print("Standard Deviation:", np.std(arr1))
print("Variance:", np.var(arr1))
print("Min:", np.min(arr1))
print("Max:", np.max(arr1))


Statistics for arr1: [ 1 22 57 33]
Mean: 28.25
Standard Deviation: 20.191272867256288
Variance: 407.6875
Min: 1
Max: 57


In [ ]:
#Logical operation